"""
domain_gap_embeddings_v3.py
==============================
All-69-patient version of domain_gap_embeddings_v2.py.

v2 was limited to the train split (~55 patients) because fake PD was only
generated for the train split. This version uses ALL 69 DESS patients and
their corresponding fake PD translations (generated by running infer2.py
without --splits/--split, i.e. on all volumes).

What is plotted (2 rows x 2 cols):
  Row 0 (t-SNE):  BEFORE: DESS vs Real PD  |  AFTER: Fake PD vs Real PD
  Row 1 (UMAP):   BEFORE: DESS vs Real PD  |  AFTER: Fake PD vs Real PD

Sampling: random per-patient (--slices_per_patient slices per volume/patient),
so every patient is represented without consecutive-slice curve artifacts.

Features: raw 64x64-downsampled pixel intensities (same compute_simple_features()
used for FID elsewhere -- no texture/learned features).

Keeps v2 untouched so both can be re-run independently.

Usage:
    python inference/domain_gap_embeddings_v3.py \
        --dess_slice_dir preprocessed_v2/slices/dess \
        --fake_pd_dir    results/stage4_fake_pd_all69 \
        --real_pd_dir    data/iu-dataset/pd-files \
        --out_png        runs/run_004/domain_gap_all69_v3.png \
        --slices_per_patient 3
"""
import argparse
import glob
import logging
import os
import sys

import numpy as np
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

try:
    import umap
    UMAP_AVAILABLE = True
except ImportError:
    UMAP_AVAILABLE = False

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from evaluate import compute_simple_features, extract_patient_id, load_slices_from_nifti
from preprocess import process_volume

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Slice samplers
# ---------------------------------------------------------------------------

def sample_dess_per_patient(dess_dir, n_per_patient, seed=42):
    """Random n_per_patient slices from every patient in dess_dir (all splits)."""
    rng = np.random.RandomState(seed)
    by_patient = {}
    for f in sorted(glob.glob(os.path.join(dess_dir, "*.npy"))):
        pid = extract_patient_id(f)
        by_patient.setdefault(pid, []).append(f)

    slices = []
    for pid, files in sorted(by_patient.items()):
        chosen = rng.choice(files, size=min(n_per_patient, len(files)), replace=False)
        for f in chosen:
            slices.append(np.load(f))

    log.info(f"  DESS: {len(by_patient)} patients, {len(slices)} slices "
             f"({n_per_patient}/patient)")
    return slices, len(by_patient)


def sample_nifti_per_volume(nifti_files, n_per_volume, modality, seed=42):
    """Random n_per_volume slices from every NIfTI volume."""
    rng = np.random.RandomState(seed)
    slices = []
    n_vols = 0
    for f in nifti_files:
        try:
            if modality == "fake_pd":
                import nibabel as nib
                vol = nib.load(f).get_fdata(dtype=np.float32)
                # shape is (384, 384, n_slices) -> transpose to (n_slices, 384, 384)
                if vol.ndim == 3 and vol.shape[2] < vol.shape[0] and vol.shape[2] < vol.shape[1]:
                    vol = np.transpose(vol, (2, 0, 1))
            else:  # real_pd — run through same preprocessing as training
                vol = process_volume(f, "PD")
        except Exception as e:
            log.warning(f"  Skipping {os.path.basename(f)}: {e}")
            continue

        n = vol.shape[0]
        idxs = rng.choice(n, size=min(n_per_volume, n), replace=False)
        for i in idxs:
            slices.append(vol[i])
        n_vols += 1

    log.info(f"  {modality}: {n_vols} volumes, {len(slices)} slices "
             f"({n_per_volume}/volume)")
    return slices, n_vols


# ---------------------------------------------------------------------------
# Embedding + metrics
# ---------------------------------------------------------------------------

def compute_separation_metrics(embedding, labels):
    return {
        "silhouette":         float(silhouette_score(embedding, labels)),
        "davies_bouldin":     float(davies_bouldin_score(embedding, labels)),
        "calinski_harabasz":  float(calinski_harabasz_score(embedding, labels)),
    }


def run_panel(ax, feats_a, feats_b, label_a, label_b,
              color_a, color_b, title, method, seed=42):
    feats  = np.concatenate([feats_a, feats_b], axis=0)
    labels = np.array([0] * len(feats_a) + [1] * len(feats_b))

    if method == "tsne":
        perp = min(30, max(5, len(feats) // 4))
        reducer = TSNE(n_components=2, random_state=seed,
                       init="pca", perplexity=perp)
    elif method == "umap":
        if not UMAP_AVAILABLE:
            ax.set_title(f"{title}\n(umap-learn not installed)")
            ax.axis("off")
            return None
        n_neighbors = min(15, max(2, len(feats) // 4))
        reducer = umap.UMAP(n_components=2, random_state=seed,
                            n_neighbors=n_neighbors)
    else:
        raise ValueError(f"Unknown method: {method}")

    emb = reducer.fit_transform(feats)

    # plot in reverse order so label_a (first / "more interesting") is on top
    ax.scatter(emb[labels == 1, 0], emb[labels == 1, 1],
               s=10, c=color_b, label=label_b, alpha=0.55, zorder=1)
    ax.scatter(emb[labels == 0, 0], emb[labels == 0, 1],
               s=10, c=color_a, label=label_a, alpha=0.75, zorder=2)

    ax.set_title(title, fontsize=11, fontweight="bold")
    ax.set_xlabel("Dim 1")
    ax.set_ylabel("Dim 2")
    ax.legend(loc="upper right", fontsize=8)

    metrics = compute_separation_metrics(emb, labels)
    text = (f"Silhouette: {metrics['silhouette']:.3f}\n"
            f"Davies-Bouldin: {metrics['davies_bouldin']:.3f}\n"
            f"Calinski-Harabasz: {metrics['calinski_harabasz']:.1f}")
    ax.text(0.02, 0.02, text, transform=ax.transAxes, fontsize=7,
            verticalalignment="bottom",
            bbox=dict(boxstyle="round", facecolor="white", alpha=0.85))
    return metrics


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dess_slice_dir",    required=True,
                    help="preprocessed_v2/slices/dess  (all splits, all patients)")
    ap.add_argument("--fake_pd_dir",       required=True,
                    help="results/stage4_fake_pd_all69  (infer2.py run on all 69)")
    ap.add_argument("--real_pd_dir",       required=True,
                    help="data/iu-dataset/pd-files  (original real PD)")
    ap.add_argument("--out_png",           required=True)
    ap.add_argument("--slices_per_patient", type=int, default=3,
                    help="Random slices per patient/volume (default 3)")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    # ---- load ---------------------------------------------------------------
    log.info("=== Loading slices (all patients, random per-patient) ===")
    log.info("DESS (all patients):")
    dess_slices, n_dess_pts = sample_dess_per_patient(
        args.dess_slice_dir, args.slices_per_patient, args.seed)

    log.info("Fake PD (all 69 translated volumes):")
    fake_files = sorted(glob.glob(os.path.join(args.fake_pd_dir, "*.nii.gz")))
    fake_slices, n_fake_vols = sample_nifti_per_volume(
        fake_files, args.slices_per_patient, "fake_pd", args.seed)

    log.info("Real PD (all volumes, preprocessed):")
    real_files = sorted(glob.glob(
        os.path.join(args.real_pd_dir, "**", "*.nii.gz"), recursive=True))
    real_slices, n_real_vols = sample_nifti_per_volume(
        real_files, args.slices_per_patient, "real_pd", args.seed)

    log.info(f"\nSummary: DESS={len(dess_slices)} slices ({n_dess_pts} patients) | "
             f"Fake PD={len(fake_slices)} slices ({n_fake_vols} vols) | "
             f"Real PD={len(real_slices)} slices ({n_real_vols} vols)")

    # ---- features -----------------------------------------------------------
    log.info("\nComputing features: raw 64x64 pixel intensities "
             "(compute_simple_features -- same as FID, no learned features)...")
    dess_feats = compute_simple_features(
        np.stack(dess_slices, axis=0)).astype(np.float64)
    fake_feats = compute_simple_features(
        np.stack(fake_slices, axis=0)).astype(np.float64)
    real_feats = compute_simple_features(
        np.stack(real_slices, axis=0)).astype(np.float64)

    # ---- plot ---------------------------------------------------------------
    methods = ["tsne", "umap"]
    fig, axes = plt.subplots(len(methods), 2, figsize=(14, 6 * len(methods)))

    fig.suptitle(
        f"Domain Gap — All 69 Patients (random {args.slices_per_patient} slices/patient)\n"
        f"Raw pixel-intensity features (64×64 flattened)",
        fontsize=13, fontweight="bold"
    )

    for row, method in enumerate(methods):
        m = method.upper()

        log.info(f"\n=== {m}: BEFORE (DESS vs Real PD) ===")
        metrics_before = run_panel(
            axes[row, 0],
            dess_feats, real_feats,
            "DESS", "Real PD",
            "tab:red", "tab:green",
            f"{m} BEFORE: DESS vs Real PD",
            method, args.seed
        )
        if metrics_before:
            log.info(f"  {metrics_before}")

        log.info(f"=== {m}: AFTER (Fake PD vs Real PD) ===")
        metrics_after = run_panel(
            axes[row, 1],
            fake_feats, real_feats,
            "Fake PD", "Real PD",
            "tab:red", "tab:green",
            f"{m} AFTER: Fake PD vs Real PD",
            method, args.seed
        )
        if metrics_after:
            log.info(f"  {metrics_after}")
            if metrics_before and metrics_after["silhouette"] < metrics_before["silhouette"]:
                log.info(f"  [{m}] Silhouette decreased after translation "
                         f"({metrics_before['silhouette']:.3f} -> "
                         f"{metrics_after['silhouette']:.3f}) -- domain gap reduced.")

    plt.tight_layout()
    os.makedirs(os.path.dirname(os.path.abspath(args.out_png)), exist_ok=True)
    plt.savefig(args.out_png, dpi=150)
    log.info(f"\nSaved -> {args.out_png}")


if __name__ == "__main__":
    main()
