"""
finetune_meniscus.py
======================
Fine-tunes the pitthexai/Knee_MRI_Segmentation_2.5D pretrained checkpoint
(baseline_best_model.pth: smp.Unet, resnet34 encoder, in_channels=3, classes=5)
for OUR narrower 3-class task: 0=background, 1=lateral meniscus, 2=medial
meniscus -- on pseudo-PD slices generated by the RegGAN pipeline.

Since the pretrained checkpoint's final segmentation head outputs 5 classes
and ours needs 3, the head is REPLACED (new randomly-initialized Conv2d),
while the ResNet34 encoder + U-Net decoder weights are loaded from the
pretrained checkpoint and fine-tuned (not frozen, since pseudo-PD's
appearance differs from their OAI-dataset images -- the encoder needs to
adapt too, not just the final classifier).

Requires: pip install segmentation-models-pytorch

Usage:
    python segmentation/finetune_meniscus.py \
        --pretrained_ckpt /path/to/baseline_best_model.pth \
        --data_root /N/project/prostate_cancer_ai/anshika/regGAN/segmentation_data \
        --out_dir   /N/project/prostate_cancer_ai/anshika/regGAN/segmentation_runs/run_001 \
        --epochs 20 --batch_size 8 --lr 1e-5
"""
import argparse
import logging
import os

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

import segmentation_models_pytorch as smp

import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dataset_2_5d import Meniscus2_5DDataset

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

N_CLASSES = 3  # background, lateral meniscus, medial meniscus
PRETRAINED_N_CLASSES = 5  # the reference repo's original output classes


def build_model(pretrained_ckpt=None, device="cpu"):
    # Build with the PRETRAINED checkpoint's original class count first, so
    # the state_dict loads cleanly into every layer including the head.
    model = smp.Unet(
        encoder_name="resnet34",
        encoder_weights="imagenet" if pretrained_ckpt is None else None,
        in_channels=3,
        classes=PRETRAINED_N_CLASSES,
    )

    if pretrained_ckpt:
        state = torch.load(pretrained_ckpt, map_location=device)
        model.load_state_dict(state)
        log.info(f"Loaded pretrained weights from {pretrained_ckpt}")

    # Replace the final segmentation head: smp.Unet's head is a Conv2d
    # mapping decoder output channels -> classes. Find it and swap the
    # output channel count, keeping the input channel count (decoder
    # feature width) the same -- new layer, randomly initialized.
    old_head = model.segmentation_head[0]
    new_head = nn.Conv2d(
        old_head.in_channels, N_CLASSES,
        kernel_size=old_head.kernel_size,
        stride=old_head.stride,
        padding=old_head.padding,
    )
    model.segmentation_head[0] = new_head
    log.info(f"Replaced segmentation head: {PRETRAINED_N_CLASSES} -> {N_CLASSES} classes")

    return model.to(device)


def dice_per_class(preds, targets, n_classes=N_CLASSES, eps=1e-6):
    """preds, targets: (B, H, W) integer class maps."""
    dices = []
    for c in range(n_classes):
        p = (preds == c).float()
        t = (targets == c).float()
        inter = (p * t).sum()
        union = p.sum() + t.sum()
        dices.append(((2 * inter + eps) / (union + eps)).item())
    return dices


def run_epoch(model, loader, optimizer, loss_fn, device, train=True):
    model.train() if train else model.eval()
    total_loss = 0.0
    dice_sums = [0.0] * N_CLASSES
    n_batches = 0

    with torch.set_grad_enabled(train):
        for batch in loader:
            x = batch["image"].to(device)
            y = batch["mask"].to(device)

            preds = model(x)
            loss = loss_fn(preds, y)

            if train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            total_loss += loss.item()
            pred_cls = preds.argmax(dim=1)
            dices = dice_per_class(pred_cls, y)
            for c in range(N_CLASSES):
                dice_sums[c] += dices[c]
            n_batches += 1

    mean_loss = total_loss / max(n_batches, 1)
    mean_dices = [d / max(n_batches, 1) for d in dice_sums]
    return mean_loss, mean_dices


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pretrained_ckpt", required=True)
    ap.add_argument("--data_root", required=True,
                     help="Root containing train/images, train/masks, val/images, val/masks "
                          "(output of prepare_meniscus_masks.py)")
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--epochs", type=int, default=20)
    ap.add_argument("--batch_size", type=int, default=8)
    ap.add_argument("--lr", type=float, default=1e-5,
                     help="Lower than from-scratch training (1e-4) -- fine-tuning "
                          "an already domain-relevant checkpoint")
    ap.add_argument("--num_workers", type=int, default=4)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    log.info(f"Using device: {device}")

    model = build_model(args.pretrained_ckpt, device)

    train_ds = Meniscus2_5DDataset(
        os.path.join(args.data_root, "train", "images"),
        os.path.join(args.data_root, "train", "masks"),
    )
    val_ds = Meniscus2_5DDataset(
        os.path.join(args.data_root, "val", "images"),
        os.path.join(args.data_root, "val", "masks"),
    )
    log.info(f"Train slices: {len(train_ds)}  Val slices: {len(val_ds)}")

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                               num_workers=args.num_workers)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                             num_workers=args.num_workers)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    loss_fn = nn.CrossEntropyLoss()

    best_val_dice = -1.0
    for epoch in range(args.epochs):
        train_loss, train_dices = run_epoch(model, train_loader, optimizer, loss_fn, device, train=True)
        val_loss, val_dices = run_epoch(model, val_loader, optimizer, loss_fn, device, train=False)

        mean_meniscus_dice = (val_dices[1] + val_dices[2]) / 2  # exclude background
        log.info(
            f"Epoch {epoch:03d}  train_loss={train_loss:.4f}  val_loss={val_loss:.4f}  "
            f"val_dice[bg={val_dices[0]:.3f} lat={val_dices[1]:.3f} med={val_dices[2]:.3f}]  "
            f"mean_meniscus_dice={mean_meniscus_dice:.4f}"
        )

        torch.save(model.state_dict(), os.path.join(args.out_dir, "ckpt_latest.pth"))
        if mean_meniscus_dice > best_val_dice:
            best_val_dice = mean_meniscus_dice
            torch.save(model.state_dict(), os.path.join(args.out_dir, "ckpt_best.pth"))
            log.info(f"  New best mean meniscus dice: {best_val_dice:.4f} -- saved ckpt_best.pth")

    log.info(f"Fine-tuning complete. Best mean meniscus dice: {best_val_dice:.4f}")


if __name__ == "__main__":
    main()
